CAPS_WORD_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_TAPPING_TERM_ENABLE = yes

KRACKO_HOME_ROW_MODS ?= yes
KRACKO_USE_COLEMAK_DH_BASE_LAYER ?= no

ifeq ($(strip $(KRACKO_HOME_ROW_MODS)), yes)
	OPT_DEFS += -DKRACKO_HOME_ROW_MODS
endif

ifeq ($(strip $(KRACKO_USE_COLEMAK_DH_BASE_LAYER)), yes)
	OPT_DEFS += -DKRACKO_USE_COLEMAK_DH_BASE_LAYER
endif
